In [1]:
import numpy as np
# np is called alias which basically means short form

In [7]:
np.array([1,2,3,4,5])    
# syntax = np.array(paas the list in third bracket)
# 1d array

array([1, 2, 3, 4, 5])

In [8]:
np.array([[1,3,4],[4,42,2]])
# syntax = np.array([in this master thrid bracket pass 2 list which they themself are in their third brackets])
# 2d array

array([[ 1,  3,  4],
       [ 4, 42,  2]])

In [143]:
np.array([[1,2,3,4],[4,3,2,1],[123,123,243,342]])
# 3d array

array([[  1,   2,   3,   4],
       [  4,   3,   2,   1],
       [123, 123, 243, 342]])

In [23]:
# 5,6 matrix
a = np.random.randint(30, size = (5,6))
# this is a matrix of 2 dimensions which has elements of random integers, from 0 to 30, with 5 rows and 6 columns.
aa = np.random.randint(low = 10, high = 50)
# we can even choose random numbers from say 10 to 50 just we have to give a tuple to the arguments low and high and make the matrix as needed
# number of third brackets = number of dimensions

In [152]:
aa

33

In [24]:
a

array([[ 5,  9, 28,  2, 13,  9],
       [ 6,  3, 27, 23,  8, 15],
       [ 3,  8, 12, 12, 18, 20],
       [ 8, 10,  6,  5, 15, 24],
       [24, 19, 14, 21,  6,  2]])

In [154]:
a.size
# size = cardinality of elements or number of elements

30

In [155]:
a.shape
# number of rows and columns of two dimensional array

(5, 6)

In [156]:
arr = np.array([np.random.randint(30, size = (5,6))])

In [157]:
arr

array([[[10, 15,  9, 25, 26, 18],
        [26, 11, 21,  4, 25,  5],
        [23,  5, 29,  8, 21, 10],
        [ 6,  8, 21,  4, 25, 16],
        [19, 26, 24, 16,  8, 13]]])

In [158]:
arr.size

30

In [159]:
arr.shape

# this is number of arrays in 3 dimensional matrix space where this a 5 by 6 array and there are three dimension or 3 data sheets each with shape 5 by 6 
# just that other two datasheets under it are empty

(1, 5, 6)

In [112]:
shape = (2,5,6)
full = np.full(shape, arr)

# this is broadcasting

NameError: name 'arr' is not defined

In [162]:
full

# this means that there are two data sheets hence 2 dimensions stacked on top of each other, also there is no need to 
# define shape as an another varaible you can directly write the tuple instead of full function
# `arr` has shape (1,5,6), meaning it has an extra first dimension.
# When we use np.full((2,5,6), arr), NumPy **broadcasts** `arr` along the first axis.
# This results in two identical copies of `arr`, effectively "stacking" them.
# If `arr` had shape (5,6) instead of (1,5,6), this would have raised an error.

array([[[10, 15,  9, 25, 26, 18],
        [26, 11, 21,  4, 25,  5],
        [23,  5, 29,  8, 21, 10],
        [ 6,  8, 21,  4, 25, 16],
        [19, 26, 24, 16,  8, 13]],

       [[10, 15,  9, 25, 26, 18],
        [26, 11, 21,  4, 25,  5],
        [23,  5, 29,  8, 21, 10],
        [ 6,  8, 21,  4, 25, 16],
        [19, 26, 24, 16,  8, 13]]])

In [35]:
a.dtype

# by default all arrays are saved in int 32

dtype('int32')

In [51]:
exp = np.random.randint(29, size = (5,6))

In [56]:
exp.dtype = np.float32

In [57]:
exp.dtype

dtype('float32')

In [40]:
emparr = np.empty((2,3,3), dtype = np.int16)

In [41]:
emparr

# this is another way to make any matrix with preffered data type

array([[[     0,      0,      0],
        [     0, -13216,  12112],
        [   481,      0, -15456]],

       [[ 12112,    481,      0],
        [-13376,  12112,    481],
        [     0,    111,    118]]], dtype=int16)

In [42]:
emparr.dtype

dtype('int16')

In [89]:
arr.astype(np.int64)

# name of array . astype (numpy . int/float 2,4,8,16,32,64....)

array([[[27, 18, 27, 11, 24,  4],
        [ 0,  7, 23, 23,  7, 16],
        [26,  6, 24,  0,  9, 12],
        [28,  9, 14, 21,  8, 29],
        [ 4,  6,  0, 16, 27, 22]]], dtype=int64)

In [95]:
arr.dtype = np.int64

In [96]:
arr.dtype

dtype('int64')

In [ ]:
# two methods to change the data type of the array
# to change data type in that cell - as type
# to change everywhere - arr.dtype = np.the said data value( could be int/float 2 4 8 16 32 64 128....)

In [74]:
sarr = np.random.randint(36, size=(6,6))

In [75]:
sarr

array([[ 2, 11, 22,  2, 23, 32],
       [24,  0,  9, 11, 35, 25],
       [ 2, 33,  4, 29,  8, 22],
       [21, 15, 16, 11, 28,  5],
       [16, 28, 19,  8, 34, 22],
       [35, 19, 23, 26, 29, 15]])

In [64]:
sarr[4,5]
# array name [number of that row, number of that column]
# this is indexing

4

In [107]:
sarr[::2, 2:5]
# syntax = array [before the comma there is information of range of rows you want to select, and after the comma the information is how many columns you want to select]
# simple slicing
# general form of slicing = array[start:stop:skip,  start:stop:skip]
#                           array[::,::]
# this is slicing

array([[22,  2, 23],
       [ 4, 29,  8],
       [19,  8, 34]])

In [87]:
two = sarr[sarr>2]
# array[array logical operation \comparision operation]
# name of array[name of that same array | logical opearation]

In [89]:
two

array([32, 35, 33, 29, 28, 28, 34, 35, 26, 29])

In [94]:
two.reshape(5,2)

# an array can only be shaped into the multiples of size of that array so here size of 'two' was 22 which means there are 
# 22 elements in that array and so it can be arranged in shape of 2 rows and 11 columns or 11 rows and 2 columns

# similarly for size 40 it can be arranged as 1,40 ; 2,20 ; 4,10 ; 5,8 ; 10,4 and blah blah blah you get it

array([[32, 35],
       [33, 29],
       [28, 28],
       [34, 35],
       [26, 29]])

In [ ]:
 2, 11, 22,  2, 23, 32],
       [24,  0,  9, 11, 35, 25],
       [ 2, 33,  4, 29,  8, 22],
       [21, 15, 16, 11, 28,  5],
       [16, 28, 19,  8, 34, 22],
       [35, 19, 23, 26, 29, 15

In [97]:
sarr[::2, ::3]
# this skips every second row and every 3 column

array([[ 2,  2],
       [ 2, 29],
       [16,  8]])

In [109]:
# array [ start : stop : skip]    syntax for 

In [98]:
sarr[:,::3]

array([[ 2,  2],
       [24, 11],
       [ 2, 29],
       [21, 11],
       [16,  8],
       [35, 26]])

In [108]:
sarr[[1,3,5], 0:3]
# advanced slicing
# this selects row 1 and 3 and 5 with columns from 0 to 3
# array[[list of all those rows that we want],range of columns]

# bring me students with even roll number and their marks in phys math chem

array([[24,  0,  9],
       [21, 15, 16],
       [35, 19, 23]])

In [135]:
sarr[1:4,[1,3,5]]

array([[ 7, 24, 23],
       [ 0, 19, 27],
       [24, 30, 33]])

In [111]:
sarr[[1,4,3],[2,5,3]]
# this will return r12 and r45

array([ 9, 22, 11])

In [123]:
sarr3 = np.array([np.random.randint(1,10,size=(6,6))])

In [124]:
sarr3

array([[[2, 4, 1, 1, 7, 8],
        [7, 1, 2, 9, 7, 9],
        [2, 3, 1, 5, 7, 4],
        [9, 7, 9, 2, 8, 4],
        [9, 9, 6, 7, 4, 1],
        [6, 8, 6, 3, 1, 9]]])

this the syntax when we have more than 1 dimension

In [125]:
sarr3[:, 1:4, 2:5]

array([[[2, 9, 7],
        [1, 5, 7],
        [9, 2, 8]]])

In [99]:
sarr5m = np.array([np.random.randint(9, size = (3,3)) for _ in range(5)])

In [100]:
sarr5m

array([[[1, 1, 3],
        [2, 0, 5],
        [6, 3, 7]],

       [[4, 2, 3],
        [0, 5, 5],
        [5, 0, 4]],

       [[7, 3, 2],
        [5, 6, 1],
        [8, 0, 2]],

       [[3, 6, 7],
        [1, 0, 2],
        [0, 0, 8]],

       [[2, 5, 7],
        [6, 6, 1],
        [6, 3, 0]]])

this is 5 matrix of size 3 by 3        another way of making multidimensional way array, this is the third way of making multidimensional array, know about it all and use what is instructed

In [137]:
sarr5m[2,1,1]

6

In [138]:
sarr5m[1:4, 1:2, 0:1]

array([[[0]],

       [[5]],

       [[1]]])

In [128]:
ar = np.arange(22)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21])

In [133]:
ar.reshape(1,2,11)

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]]])

In [134]:
aarr = np.random.randint(14 , size = (2,7))
barr = np.random.randint(14 , size = (2,7))

in element wise operation multiple arrays are given in argument then a comparing operator is given element aij and bij are compared then a boolean is returned as provided by logic

In [135]:
aarr

array([[ 4,  0, 13,  0,  0,  7,  4],
       [10,  7,  7,  3, 12, 13,  7]])

In [136]:
barr

array([[ 3,  3,  4,  9,  6,  2,  9],
       [ 2,  3,  3, 12,  3, 12, 13]])

In [137]:
(aarr > barr)

array([[ True, False,  True, False, False,  True, False],
       [ True,  True,  True, False,  True,  True, False]])

In [138]:
(aarr == barr)

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False]])

In [139]:
(aarr <= barr)

array([[False,  True, False,  True,  True, False,  True],
       [False, False, False,  True, False, False,  True]])

these were element wise comparision

In [140]:
# these are logical operations like logic gates & and, | or, ~ not
# and = &
# or = |
# bot = ~
(aarr > 4) & (barr > 8)

array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True]])

In [141]:
(aarr >1 ) | (barr > 3)

array([[ True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])

In [142]:
(~(aarr < barr))

array([[ True, False,  True, False, False,  True, False],
       [ True,  True,  True, False,  True,  True, False]])

In [12]:
(aarr<barr)

array([[False, False, False, False, False,  True,  True],
       [ True,  True, False, False,  True,  True, False]])

In [143]:
np.where(aarr<barr, aarr, barr)

array([[ 3,  0,  4,  0,  0,  2,  4],
       [ 2,  3,  3,  3,  3, 12,  7]])

np dot where is a function which takes a condition and the two arrays and does the operation and returns which element either aij or bij satisfies it,
in this example the smaller number was supposed to be found between the two arrays

and we can also return a new value if the condition is not meant say if we want all failed students who failed get marked F rather than showing their numbers so we will run the function 
np.where(array<less than passing marks, 'f', array),see below

In [156]:
np.where(aarr< 5,  True, aarr)

array([[ 1,  1, 13,  1,  1,  7,  1],
       [10,  7,  7,  1, 12, 13,  7]])

In [19]:
aarr.reshape(7,2)

array([[12,  8],
       [10,  5],
       [ 0,  3],
       [ 5,  6],
       [13,  2],
       [13, 13],
       [ 2, 11]])

In [23]:
aarr.flatten()

array([12,  8, 10,  5,  0,  3,  5,  6, 13,  2, 13, 13,  2, 11])

In [157]:
aarr.T    

array([[ 4, 10],
       [ 0,  7],
       [13,  7],
       [ 0,  3],
       [ 0, 12],
       [ 7, 13],
       [ 4,  7]])

In [158]:
np.transpose(aarr)

array([[ 4, 10],
       [ 0,  7],
       [13,  7],
       [ 0,  3],
       [ 0, 12],
       [ 7, 13],
       [ 4,  7]])

In [25]:
aarr.reshape(2,7)

array([[12,  8, 10,  5,  0,  3,  5],
       [ 6, 13,  2, 13, 13,  2, 11]])

In [27]:
rearr = np.random.randint(40, size = (5,8))

In [28]:
rearr

array([[29,  4, 11, 14,  5, 12, 35, 34],
       [ 0, 19,  2,  3, 17, 13,  7, 18],
       [26, 20,  2, 28, 27,  5, 28, 12],
       [12,  6, 38, 17,  1,  3,  6,  6],
       [ 0,  2,  3, 18,  4, 22, 20, 13]])

In [29]:
rearr.reshape(20,2)

array([[29,  4],
       [11, 14],
       [ 5, 12],
       [35, 34],
       [ 0, 19],
       [ 2,  3],
       [17, 13],
       [ 7, 18],
       [26, 20],
       [ 2, 28],
       [27,  5],
       [28, 12],
       [12,  6],
       [38, 17],
       [ 1,  3],
       [ 6,  6],
       [ 0,  2],
       [ 3, 18],
       [ 4, 22],
       [20, 13]])

In [30]:
rearr.reshape(10,4)

array([[29,  4, 11, 14],
       [ 5, 12, 35, 34],
       [ 0, 19,  2,  3],
       [17, 13,  7, 18],
       [26, 20,  2, 28],
       [27,  5, 28, 12],
       [12,  6, 38, 17],
       [ 1,  3,  6,  6],
       [ 0,  2,  3, 18],
       [ 4, 22, 20, 13]])

In [32]:
np.resize(rearr, 20)

array([29,  4, 11, 14,  5, 12, 35, 34,  0, 19,  2,  3, 17, 13,  7, 18, 26,
       20,  2, 28])

In [ ]:
# np.resize instead of changing the shape changes the size, say here we 40 elements and then we resized it to 20 so it took the first 20 elements and returned us that
# and np.newaxis gives it another axis, it can be used to change a row vector into column vector and vise versa, here rearr was 2d and then we passed the function as name of array, 
# at which postion we want the new axis in then np.name of the array
# another way of getting a new dimension is np.expand_dims()

In [33]:
rearr[:, np.newaxis]

array([[[29,  4, 11, 14,  5, 12, 35, 34]],

       [[ 0, 19,  2,  3, 17, 13,  7, 18]],

       [[26, 20,  2, 28, 27,  5, 28, 12]],

       [[12,  6, 38, 17,  1,  3,  6,  6]],

       [[ 0,  2,  3, 18,  4, 22, 20, 13]]])

In [159]:
np.hstack((aarr, barr))

array([[ 4,  0, 13,  0,  0,  7,  4,  3,  3,  4,  9,  6,  2,  9],
       [10,  7,  7,  3, 12, 13,  7,  2,  3,  3, 12,  3, 12, 13]])

In [160]:
np.vstack((aarr,barr))

array([[ 4,  0, 13,  0,  0,  7,  4],
       [10,  7,  7,  3, 12, 13,  7],
       [ 3,  3,  4,  9,  6,  2,  9],
       [ 2,  3,  3, 12,  3, 12, 13]])

In [ ]:
# np.hstack and vstack joins two arrays horizontally and vertically as the name suggest and concatenate is that but with additional arguments like which axis to join them to and so on

In [161]:
np.concatenate((aarr, barr), axis = 0)

array([[ 4,  0, 13,  0,  0,  7,  4],
       [10,  7,  7,  3, 12, 13,  7],
       [ 3,  3,  4,  9,  6,  2,  9],
       [ 2,  3,  3, 12,  3, 12, 13]])

In [162]:
np.concatenate((aarr, barr), axis = 1)

array([[ 4,  0, 13,  0,  0,  7,  4,  3,  3,  4,  9,  6,  2,  9],
       [10,  7,  7,  3, 12, 13,  7,  2,  3,  3, 12,  3, 12, 13]])

In [43]:
np.split(aarr,2)

[array([[12,  8, 10,  5,  0,  3,  5]]), array([[ 6, 13,  2, 13, 13,  2, 11]])]

In [ ]:
# np.split splits an array into equal parts of the said number when given to the argument 'indices' and if it can not an error is raised, np.array_split is advanced it splits the array into the sub array even
# if has to give uneven or empty arrays and both the funtion can have the parameter axis along which the split must be made

In [167]:
np.array_split(aarr, 7.3)

[array([[ 4,  0, 13,  0,  0,  7,  4]]),
 array([[10,  7,  7,  3, 12, 13,  7]]),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32),
 array([], shape=(0, 7), dtype=int32)]

In [168]:
aarr

array([[ 4,  0, 13,  0,  0,  7,  4],
       [10,  7,  7,  3, 12, 13,  7]])

In [169]:
np.sort(aarr)

array([[ 0,  0,  0,  4,  4,  7, 13],
       [ 3,  7,  7,  7, 10, 12, 13]])

In [175]:
np.sort(aarr, axis = 0, kind = 'quick')

array([[ 4,  0,  7,  0,  0,  7,  4],
       [10,  7, 13,  3, 12, 13,  7]])

In [ ]:
# well, it sorts the array, and axis , type of sorting can be chosen by the user such as bubble or merge sort, ascending descending and so

as of now the syntax and api should have been clear but here is the summary


np . function (array, parameters required by the function to do the calulation)


ways to make multi dimensional arrays are
mannual method
creating random intgers or just ones and zeros using np.ones/ np.zeros and then choosing the size
the size parameter takes a tuple which as (dimensions, rows, columns)
np.full just duplicates the array that many times

will add more methods if i can remember them later on